camunda:
  client:
    mode: self-managed
    zeebe:
      enabled: true
      grpc-address: http://localhost:26500
      rest-address: http://localhost:9600
      prefer-rest-over-grpc: false


server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/example_database
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

logging:
  level:
    io.camunda.zeebe.client.impl.ZeebeCallCredentials: ERROR
