camunda:
  client:
    mode: self-managed
    prefer-rest-over-grpc: false
    rest-address: http://localhost:9600
    grpc-address: http://localhost:26500
    enabled: true
    auth:
      method: none

server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/example_database
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

logging:
  level:
    io.camunda.zeebe.client.impl.ZeebeCallCredentials: ERROR
