// Generated by bpmn-to-code
@file:Suppress("unused")

package io.miragon.example.adapter.process

import io.miragon.bpmn.runtime.BpmnEngine
import io.miragon.bpmn.runtime.BpmnFlow
import io.miragon.bpmn.runtime.BpmnRelations
import io.miragon.bpmn.runtime.BpmnTimer
import io.miragon.bpmn.runtime.ElementId
import io.miragon.bpmn.runtime.MessageName
import io.miragon.bpmn.runtime.ProcessId
import io.miragon.bpmn.runtime.VariableName
import kotlin.String
import kotlin.Suppress

object InnerCircleMembershipProcessApi {
  val PROCESS_ID: ProcessId = ProcessId("inner-circle-membership")

  val PROCESS_ENGINE: BpmnEngine = BpmnEngine.ZEEBE

  /**
   * BPMN element ids as declared in the source model.
   * Typically used in process-level tests or when searching for tasks.
   * Worker runtime code rarely needs these.
   */
  object Elements {
    val END_EVENT_CONFIRMATION_EXPIRED: ElementId = ElementId("endEvent_confirmationExpired")

    val END_EVENT_MAIL_SENT_AGAIN: ElementId = ElementId("endEvent_mailSentAgain")

    val END_EVENT_MEMBERSHIP_ACTIVATED: ElementId = ElementId("endEvent_membershipActivated")

    val END_EVENT_MEMBERSHIP_CONFIRMED: ElementId = ElementId("endEvent_membershipConfirmed")

    val END_EVENT_MEMBERSHIP_DECLINED: ElementId = ElementId("endEvent_membershipDeclined")

    val END_EVENT_MEMBERSHIP_REJECTED: ElementId = ElementId("endEvent_membershipRejected")

    val EVENT_CONFIRMATION_REJECTED: ElementId = ElementId("event_confirmationRejected")

    val GATEWAY_HAS_EMPTY_SPOTS: ElementId = ElementId("gateway_hasEmptySpots")

    val RECEIVE_TASK_CONFIRM_MEMBERSHIP: ElementId =
        ElementId("receiveTask_confirmMembership")

    val SERVICE_TASK_CLAIM_MEMBERSHIP: ElementId = ElementId("serviceTask_claimMembership")

    val SERVICE_TASK_RESEND_CONFIRMATION_MAIL: ElementId =
        ElementId("serviceTask_resendConfirmationMail")

    val SERVICE_TASK_SEND_CONFIRMATION_MAIL: ElementId =
        ElementId("serviceTask_sendConfirmationMail")

    val SERVICE_TASK_SEND_REJECTION_MAIL: ElementId =
        ElementId("serviceTask_sendRejectionMail")

    val SERVICE_TASK_SEND_WELCOME_MAIL: ElementId = ElementId("serviceTask_sendWelcomeMail")

    val START_EVENT_CONFIRMATION_REQUIRED: ElementId =
        ElementId("startEvent_confirmationRequired")

    val START_EVENT_REGISTRATION_SUBMITTED: ElementId =
        ElementId("startEvent_registrationSubmitted")

    val SUB_PROCESS_CONFIRM_MEMBERSHIP: ElementId = ElementId("subProcess_confirmMembership")

    val TIMER_EVENT_ABORT_AFTER_DEADLINE: ElementId =
        ElementId("timerEvent_abortAfterDeadline")

    val TIMER_EVENT_RESEND_EVERY_DAY: ElementId = ElementId("timerEvent_resendEveryDay")
  }

  /**
   * BPMN message names used to correlate messages to running process instances.
   */
  object Messages {
    val MIRAVELO_CONFIRMATION_REJECTED: MessageName =
        MessageName("miravelo.confirmationRejected")

    val MIRAVELO_MEMBERSHIP_CONFIRMED: MessageName =
        MessageName("miravelo.membershipConfirmed")

    val MIRAVELO_REGISTRATION_SUBMITTED: MessageName =
        MessageName("miravelo.registrationSubmitted")
  }

  /**
   * Job worker task types used in `@JobWorker(type = ServiceTasks.X)` annotations.
   * Kept as `const val String` because annotation arguments must be compile-time constants.
   */
  object ServiceTasks {
    const val MEMBERSHIP_CLAIM_MEMBERSHIP: String = "membership.claimMembership"

    const val MEMBERSHIP_SEND_CONFIRMATION_MAIL: String = "membership.sendConfirmationMail"

    const val MEMBERSHIP_SEND_REJECTION_MAIL: String = "membership.sendRejectionMail"

    const val MEMBERSHIP_SEND_WELCOME_MAIL: String = "membership.sendWelcomeMail"
  }

  object Timers {
    val TIMER_EVENT_ABORT_AFTER_DEADLINE: BpmnTimer = BpmnTimer("Duration", "PT2M30S")

    val TIMER_EVENT_RESEND_EVERY_DAY: BpmnTimer = BpmnTimer("Cycle", "R/PT1M")
  }

  /**
   * Process variables grouped by the BPMN element that declares them.
   * Direction is encoded in each variable's wrapper type: `VariableName.Input`, `VariableName.Output`, or `VariableName.InOut` when the variable is both read and written by the same element.
   * Consumer APIs that take a specific subtype (e.g. `fun setOutput(v: VariableName.Output)`) get compile-time direction enforcement.
   */
  object Variables {
    object ServiceTaskClaimMembership {
      val HAS_EMPTY_SPOTS: VariableName.Output = VariableName.Output("hasEmptySpots")
    }

    object StartEventRegistrationSubmitted {
      val MEMBERSHIP_ID: VariableName.Output = VariableName.Output("membershipId")
    }
  }

  /**
   * Sequence flows between BPMN elements.
   * Mainly useful for process-model tooling, tests, and AI-agent consumers reasoning about the process shape.
   * Worker code typically does not need these.
   */
  object Flows {
    val FLOW_CLAIM_TO_HAS_EMPTY_SPOTS: BpmnFlow = BpmnFlow(
          id = "flow_claimToHasEmptySpots",
          sourceRef = "serviceTask_claimMembership",
          targetRef = "gateway_hasEmptySpots",
        )

    val FLOW_CONFIRM_TO_CONFIRMED: BpmnFlow = BpmnFlow(
          id = "flow_confirmToConfirmed",
          sourceRef = "receiveTask_confirmMembership",
          targetRef = "endEvent_membershipConfirmed",
        )

    val FLOW_CONFIRMATION_MAIL_TO_CONFIRM: BpmnFlow = BpmnFlow(
          id = "flow_confirmationMailToConfirm",
          sourceRef = "serviceTask_sendConfirmationMail",
          targetRef = "receiveTask_confirmMembership",
        )

    val FLOW_CONFIRMED_TO_WELCOME_MAIL: BpmnFlow = BpmnFlow(
          id = "flow_confirmedToWelcomeMail",
          sourceRef = "subProcess_confirmMembership",
          targetRef = "serviceTask_sendWelcomeMail",
        )

    val FLOW_DEADLINE_TO_EXPIRED: BpmnFlow = BpmnFlow(
          id = "flow_deadlineToExpired",
          sourceRef = "timerEvent_abortAfterDeadline",
          targetRef = "endEvent_confirmationExpired",
        )

    val FLOW_EVERY_DAY_TO_RESEND: BpmnFlow = BpmnFlow(
          id = "flow_everyDayToResend",
          sourceRef = "timerEvent_resendEveryDay",
          targetRef = "serviceTask_resendConfirmationMail",
        )

    val FLOW_HAS_EMPTY_SPOTS_NO: BpmnFlow = BpmnFlow(
          id = "flow_hasEmptySpotsNo",
          name = "No",
          sourceRef = "gateway_hasEmptySpots",
          targetRef = "serviceTask_sendRejectionMail",
          condition = "=not(hasEmptySpots)",
        )

    val FLOW_HAS_EMPTY_SPOTS_YES: BpmnFlow = BpmnFlow(
          id = "flow_hasEmptySpotsYes",
          name = "Yes",
          sourceRef = "gateway_hasEmptySpots",
          targetRef = "subProcess_confirmMembership",
          isDefault = true,
        )

    val FLOW_REJECTED_TO_DECLINED: BpmnFlow = BpmnFlow(
          id = "flow_rejectedToDeclined",
          sourceRef = "event_confirmationRejected",
          targetRef = "endEvent_membershipDeclined",
        )

    val FLOW_REJECTION_MAIL_TO_REJECTED: BpmnFlow = BpmnFlow(
          id = "flow_rejectionMailToRejected",
          sourceRef = "serviceTask_sendRejectionMail",
          targetRef = "endEvent_membershipRejected",
        )

    val FLOW_REQUIRED_TO_CONFIRMATION_MAIL: BpmnFlow = BpmnFlow(
          id = "flow_requiredToConfirmationMail",
          sourceRef = "startEvent_confirmationRequired",
          targetRef = "serviceTask_sendConfirmationMail",
        )

    val FLOW_RESEND_TO_MAIL_SENT_AGAIN: BpmnFlow = BpmnFlow(
          id = "flow_resendToMailSentAgain",
          sourceRef = "serviceTask_resendConfirmationMail",
          targetRef = "endEvent_mailSentAgain",
        )

    val FLOW_SUBMITTED_TO_CLAIM: BpmnFlow = BpmnFlow(
          id = "flow_submittedToClaim",
          sourceRef = "startEvent_registrationSubmitted",
          targetRef = "serviceTask_claimMembership",
        )

    val FLOW_WELCOME_MAIL_TO_ACTIVATED: BpmnFlow = BpmnFlow(
          id = "flow_welcomeMailToActivated",
          sourceRef = "serviceTask_sendWelcomeMail",
          targetRef = "endEvent_membershipActivated",
        )
  }

  /**
   * Per-element graph metadata (elementType / previousElements / followingElements / parentId / boundary attachments).
   * Intended for tooling and tests, not worker runtime code.
   */
  object Relations {
    val END_EVENT_CONFIRMATION_EXPIRED: BpmnRelations = BpmnRelations(
          name = "Confirmation expired",
          previousElements = listOf("timerEvent_abortAfterDeadline"),
          followingElements = emptyList(),
          parentId = null,
          attachedToRef = null,
          attachedElements = emptyList(),
          elementType = "END_EVENT",
        )

    val END_EVENT_MAIL_SENT_AGAIN: BpmnRelations = BpmnRelations(
          name = "Mail sent again",
          previousElements = listOf("serviceTask_resendConfirmationMail"),
          followingElements = emptyList(),
          parentId = null,
          attachedToRef = null,
          attachedElements = emptyList(),
          elementType = "END_EVENT",
        )

    val END_EVENT_MEMBERSHIP_ACTIVATED: BpmnRelations = BpmnRelations(
          name = "Membership activated",
          previousElements = listOf("serviceTask_sendWelcomeMail"),
          followingElements = emptyList(),
          parentId = null,
          attachedToRef = null,
          attachedElements = emptyList(),
          elementType = "END_EVENT",
        )

    val END_EVENT_MEMBERSHIP_CONFIRMED: BpmnRelations = BpmnRelations(
          name = "Membership confirmed",
          previousElements = listOf("receiveTask_confirmMembership"),
          followingElements = emptyList(),
          parentId = "subProcess_confirmMembership",
          attachedToRef = null,
          attachedElements = emptyList(),
          elementType = "END_EVENT",
        )

    val END_EVENT_MEMBERSHIP_DECLINED: BpmnRelations = BpmnRelations(
          name = "Membership declined",
          previousElements = listOf("event_confirmationRejected"),
          followingElements = emptyList(),
          parentId = null,
          attachedToRef = null,
          attachedElements = emptyList(),
          elementType = "END_EVENT",
        )

    val END_EVENT_MEMBERSHIP_REJECTED: BpmnRelations = BpmnRelations(
          name = "Membership rejected",
          previousElements = listOf("serviceTask_sendRejectionMail"),
          followingElements = emptyList(),
          parentId = null,
          attachedToRef = null,
          attachedElements = emptyList(),
          elementType = "END_EVENT",
        )

    val EVENT_CONFIRMATION_REJECTED: BpmnRelations = BpmnRelations(
          name = "Confirmation rejected",
          previousElements = emptyList(),
          followingElements = listOf("endEvent_membershipDeclined"),
          parentId = null,
          attachedToRef = "subProcess_confirmMembership",
          attachedElements = emptyList(),
          elementType = "MESSAGE_BOUNDARY_EVENT",
        )

    val GATEWAY_HAS_EMPTY_SPOTS: BpmnRelations = BpmnRelations(
          name = "Has empty spots?",
          previousElements = listOf("serviceTask_claimMembership"),
          followingElements = listOf("subProcess_confirmMembership", "serviceTask_sendRejectionMail"),
          parentId = null,
          attachedToRef = null,
          attachedElements = emptyList(),
          elementType = "EXCLUSIVE_GATEWAY",
        )

    val RECEIVE_TASK_CONFIRM_MEMBERSHIP: BpmnRelations = BpmnRelations(
          name = "Confirm membership",
          previousElements = listOf("serviceTask_sendConfirmationMail"),
          followingElements = listOf("endEvent_membershipConfirmed"),
          parentId = "subProcess_confirmMembership",
          attachedToRef = null,
          attachedElements = emptyList(),
          elementType = "RECEIVE_TASK",
        )

    val SERVICE_TASK_CLAIM_MEMBERSHIP: BpmnRelations = BpmnRelations(
          name = "Claim membership",
          previousElements = listOf("startEvent_registrationSubmitted"),
          followingElements = listOf("gateway_hasEmptySpots"),
          parentId = null,
          attachedToRef = null,
          attachedElements = emptyList(),
          elementType = "SERVICE_TASK",
        )

    val SERVICE_TASK_RESEND_CONFIRMATION_MAIL: BpmnRelations = BpmnRelations(
          name = "Re-send confirmation mail",
          previousElements = listOf("timerEvent_resendEveryDay"),
          followingElements = listOf("endEvent_mailSentAgain"),
          parentId = null,
          attachedToRef = null,
          attachedElements = emptyList(),
          elementType = "SERVICE_TASK",
        )

    val SERVICE_TASK_SEND_CONFIRMATION_MAIL: BpmnRelations = BpmnRelations(
          name = "Send confirmation mail",
          previousElements = listOf("startEvent_confirmationRequired"),
          followingElements = listOf("receiveTask_confirmMembership"),
          parentId = "subProcess_confirmMembership",
          attachedToRef = null,
          attachedElements = emptyList(),
          elementType = "SERVICE_TASK",
        )

    val SERVICE_TASK_SEND_REJECTION_MAIL: BpmnRelations = BpmnRelations(
          name = "Send rejection mail",
          previousElements = listOf("gateway_hasEmptySpots"),
          followingElements = listOf("endEvent_membershipRejected"),
          parentId = null,
          attachedToRef = null,
          attachedElements = emptyList(),
          elementType = "SERVICE_TASK",
        )

    val SERVICE_TASK_SEND_WELCOME_MAIL: BpmnRelations = BpmnRelations(
          name = "Send welcome mail",
          previousElements = listOf("subProcess_confirmMembership"),
          followingElements = listOf("endEvent_membershipActivated"),
          parentId = null,
          attachedToRef = null,
          attachedElements = emptyList(),
          elementType = "SERVICE_TASK",
        )

    val START_EVENT_CONFIRMATION_REQUIRED: BpmnRelations = BpmnRelations(
          name = "Confirmation required",
          previousElements = emptyList(),
          followingElements = listOf("serviceTask_sendConfirmationMail"),
          parentId = "subProcess_confirmMembership",
          attachedToRef = null,
          attachedElements = emptyList(),
          elementType = "START_EVENT",
        )

    val START_EVENT_REGISTRATION_SUBMITTED: BpmnRelations = BpmnRelations(
          name = "Registration submitted",
          previousElements = emptyList(),
          followingElements = listOf("serviceTask_claimMembership"),
          parentId = null,
          attachedToRef = null,
          attachedElements = emptyList(),
          elementType = "MESSAGE_START_EVENT",
        )

    val SUB_PROCESS_CONFIRM_MEMBERSHIP: BpmnRelations = BpmnRelations(
          name = "Confirm membership",
          previousElements = listOf("gateway_hasEmptySpots"),
          followingElements = listOf("serviceTask_sendWelcomeMail"),
          parentId = null,
          attachedToRef = null,
          attachedElements = listOf("event_confirmationRejected", "timerEvent_abortAfterDeadline", "timerEvent_resendEveryDay"),
          elementType = "SUB_PROCESS",
        )

    val TIMER_EVENT_ABORT_AFTER_DEADLINE: BpmnRelations = BpmnRelations(
          name = "After 3 1/2 days",
          previousElements = emptyList(),
          followingElements = listOf("endEvent_confirmationExpired"),
          parentId = null,
          attachedToRef = "subProcess_confirmMembership",
          attachedElements = emptyList(),
          elementType = "TIMER_BOUNDARY_EVENT",
        )

    val TIMER_EVENT_RESEND_EVERY_DAY: BpmnRelations = BpmnRelations(
          name = "Every day",
          previousElements = emptyList(),
          followingElements = listOf("serviceTask_resendConfirmationMail"),
          parentId = null,
          attachedToRef = "subProcess_confirmMembership",
          attachedElements = emptyList(),
          elementType = "TIMER_BOUNDARY_EVENT",
        )
  }
}
