// Generated by bpmn-to-code
@file:Suppress("unused")

package io.miragon.example.adapter.process

import io.miragon.bpmn.runtime.BpmnEngine
import io.miragon.bpmn.runtime.BpmnFlow
import io.miragon.bpmn.runtime.BpmnRelations
import io.miragon.bpmn.runtime.BpmnTimer
import io.miragon.bpmn.runtime.ElementId
import io.miragon.bpmn.runtime.MessageName
import io.miragon.bpmn.runtime.ProcessId
import io.miragon.bpmn.runtime.VariableName
import kotlin.String
import kotlin.Suppress

object NewsletterSubscriptionProcessApi {
  val PROCESS_ID: ProcessId = ProcessId("newsletter-subscription")

  val PROCESS_ENGINE: BpmnEngine = BpmnEngine.ZEEBE

  /**
   * BPMN element ids as declared in the source model.
   * Typically used in process-level tests or when searching for tasks.
   * Worker runtime code rarely needs these.
   */
  object Elements {
    val END_EVENT_REGISTRATION_ABORTED: ElementId = ElementId("endEvent_registrationAborted")

    val END_EVENT_REGISTRATION_COMPLETED: ElementId =
        ElementId("endEvent_registrationCompleted")

    val END_EVENT_SUBSCRIPTION_CONFIRMED: ElementId =
        ElementId("endEvent_subscriptionConfirmed")

    val EVENT_AFTER_3_DAYS: ElementId = ElementId("event_after3Days")

    val EVENT_EVERY_DAY: ElementId = ElementId("event_everyDay")

    val GATEWAY_RESEND_REMINDER: ElementId = ElementId("gateway_resendReminder")

    val RECEIVE_TASK_CONFIRM_REGISTRATION: ElementId =
        ElementId("receiveTask_confirmRegistration")

    val SERVICE_TASK_ABORT_REGISTRATION: ElementId =
        ElementId("serviceTask_abortRegistration")

    val SERVICE_TASK_SEND_CONFIRMATION_MAIL: ElementId =
        ElementId("serviceTask_sendConfirmationMail")

    val SERVICE_TASK_SEND_WELCOME_MAIL: ElementId = ElementId("serviceTask_sendWelcomeMail")

    val START_EVENT_REQUEST_RECEIVED: ElementId = ElementId("startEvent_requestReceived")

    val START_EVENT_SUBMIT_REGISTRATION_FORM: ElementId =
        ElementId("startEvent_submitRegistrationForm")

    val SUB_PROCESS_CONFIRMATION: ElementId = ElementId("subProcess_confirmation")
  }

  /**
   * BPMN message names used to correlate messages to running process instances.
   */
  object Messages {
    val MESSAGE_FORM_SUBMITTED: MessageName = MessageName("Message_FormSubmitted")

    val MESSAGE_SUBSCRIPTION_CONFIRMED: MessageName =
        MessageName("Message_SubscriptionConfirmed")
  }

  /**
   * Job worker task types used in `@JobWorker(type = ServiceTasks.X)` annotations.
   * Kept as `const val String` because annotation arguments must be compile-time constants.
   */
  object ServiceTasks {
    const val NEWSLETTER_ABORT_REGISTRATION: String = "newsletter.abortRegistration"

    const val NEWSLETTER_REGISTRATION_COMPLETED: String = "newsletter.registrationCompleted"

    const val NEWSLETTER_SEND_CONFIRMATION_MAIL: String = "newsletter.sendConfirmationMail"

    const val NEWSLETTER_SEND_WELCOME_MAIL: String = "newsletter.sendWelcomeMail"
  }

  object Timers {
    val EVENT_AFTER_3_DAYS: BpmnTimer = BpmnTimer("Duration", "PT2M30S")

    val EVENT_EVERY_DAY: BpmnTimer = BpmnTimer("Duration", "PT1M")
  }

  /**
   * Process variables grouped by the BPMN element that declares them.
   * Direction is encoded in each variable's wrapper type: `VariableName.Input`, `VariableName.Output`, or `VariableName.InOut` when the variable is both read and written by the same element.
   * Consumer APIs that take a specific subtype (e.g. `fun setOutput(v: VariableName.Output)`) get compile-time direction enforcement.
   */
  object Variables {
    object EndEventRegistrationCompleted {
      val SUBSCRIPTION_ID: VariableName.Output = VariableName.Output("subscriptionId")
    }

    object StartEventRequestReceived {
      val SUBSCRIPTION_ID: VariableName.Output = VariableName.Output("subscriptionId")
    }

    object StartEventSubmitRegistrationForm {
      val SUBSCRIPTION_ID: VariableName.Output = VariableName.Output("subscriptionId")
    }
  }

  /**
   * Sequence flows between BPMN elements.
   * Mainly useful for process-model tooling, tests, and AI-agent consumers reasoning about the process shape.
   * Worker code typically does not need these.
   */
  object Flows {
    val FLOW_ABORT_TO_ABORTED: BpmnFlow = BpmnFlow(
          id = "flow_abortToAborted",
          sourceRef = "serviceTask_abortRegistration",
          targetRef = "endEvent_registrationAborted",
        )

    val FLOW_AFTER_3_DAYS_TO_ABORT: BpmnFlow = BpmnFlow(
          id = "flow_after3DaysToAbort",
          sourceRef = "event_after3Days",
          targetRef = "serviceTask_abortRegistration",
        )

    val FLOW_CONFIRM_TO_CONFIRMED: BpmnFlow = BpmnFlow(
          id = "flow_confirmToConfirmed",
          sourceRef = "receiveTask_confirmRegistration",
          targetRef = "endEvent_subscriptionConfirmed",
        )

    val FLOW_CONFIRMATION_MAIL_TO_CONFIRM: BpmnFlow = BpmnFlow(
          id = "flow_confirmationMailToConfirm",
          sourceRef = "serviceTask_sendConfirmationMail",
          targetRef = "receiveTask_confirmRegistration",
        )

    val FLOW_CONFIRMATION_TO_WELCOME_MAIL: BpmnFlow = BpmnFlow(
          id = "flow_confirmationToWelcomeMail",
          sourceRef = "subProcess_confirmation",
          targetRef = "serviceTask_sendWelcomeMail",
        )

    val FLOW_EVERY_DAY_TO_MERGE: BpmnFlow = BpmnFlow(
          id = "flow_everyDayToMerge",
          sourceRef = "event_everyDay",
          targetRef = "gateway_resendReminder",
        )

    val FLOW_MERGE_TO_CONFIRMATION_MAIL: BpmnFlow = BpmnFlow(
          id = "flow_mergeToConfirmationMail",
          sourceRef = "gateway_resendReminder",
          targetRef = "serviceTask_sendConfirmationMail",
        )

    val FLOW_REQUEST_TO_MERGE: BpmnFlow = BpmnFlow(
          id = "flow_requestToMerge",
          sourceRef = "startEvent_requestReceived",
          targetRef = "gateway_resendReminder",
        )

    val FLOW_SUBMIT_TO_CONFIRMATION: BpmnFlow = BpmnFlow(
          id = "flow_submitToConfirmation",
          sourceRef = "startEvent_submitRegistrationForm",
          targetRef = "subProcess_confirmation",
        )

    val FLOW_WELCOME_MAIL_TO_COMPLETED: BpmnFlow = BpmnFlow(
          id = "flow_welcomeMailToCompleted",
          sourceRef = "serviceTask_sendWelcomeMail",
          targetRef = "endEvent_registrationCompleted",
        )
  }

  /**
   * Per-element graph metadata (elementType / previousElements / followingElements / parentId / boundary attachments).
   * Intended for tooling and tests, not worker runtime code.
   */
  object Relations {
    val END_EVENT_REGISTRATION_ABORTED: BpmnRelations = BpmnRelations(
          name = "Registration aborted",
          previousElements = listOf("serviceTask_abortRegistration"),
          followingElements = emptyList(),
          parentId = null,
          attachedToRef = null,
          attachedElements = emptyList(),
          elementType = "END_EVENT",
        )

    val END_EVENT_REGISTRATION_COMPLETED: BpmnRelations = BpmnRelations(
          name = "Registration completed",
          previousElements = listOf("serviceTask_sendWelcomeMail"),
          followingElements = emptyList(),
          parentId = null,
          attachedToRef = null,
          attachedElements = emptyList(),
          elementType = "MESSAGE_END_EVENT",
        )

    val END_EVENT_SUBSCRIPTION_CONFIRMED: BpmnRelations = BpmnRelations(
          name = "Subscription confirmed",
          previousElements = listOf("receiveTask_confirmRegistration"),
          followingElements = emptyList(),
          parentId = "subProcess_confirmation",
          attachedToRef = null,
          attachedElements = emptyList(),
          elementType = "END_EVENT",
        )

    val EVENT_AFTER_3_DAYS: BpmnRelations = BpmnRelations(
          name = "After 3 days",
          previousElements = emptyList(),
          followingElements = listOf("serviceTask_abortRegistration"),
          parentId = null,
          attachedToRef = "subProcess_confirmation",
          attachedElements = emptyList(),
          elementType = "TIMER_BOUNDARY_EVENT",
        )

    val EVENT_EVERY_DAY: BpmnRelations = BpmnRelations(
          name = "Every day",
          previousElements = emptyList(),
          followingElements = listOf("gateway_resendReminder"),
          parentId = "subProcess_confirmation",
          attachedToRef = "receiveTask_confirmRegistration",
          attachedElements = emptyList(),
          elementType = "TIMER_BOUNDARY_EVENT",
        )

    val GATEWAY_RESEND_REMINDER: BpmnRelations = BpmnRelations(
          previousElements = listOf("startEvent_requestReceived", "event_everyDay"),
          followingElements = listOf("serviceTask_sendConfirmationMail"),
          parentId = "subProcess_confirmation",
          attachedToRef = null,
          attachedElements = emptyList(),
          elementType = "EXCLUSIVE_GATEWAY",
        )

    val RECEIVE_TASK_CONFIRM_REGISTRATION: BpmnRelations = BpmnRelations(
          name = "Confirm subscription",
          previousElements = listOf("serviceTask_sendConfirmationMail"),
          followingElements = listOf("endEvent_subscriptionConfirmed"),
          parentId = "subProcess_confirmation",
          attachedToRef = null,
          attachedElements = listOf("event_everyDay"),
          elementType = "RECEIVE_TASK",
        )

    val SERVICE_TASK_ABORT_REGISTRATION: BpmnRelations = BpmnRelations(
          name = "Abort registration",
          previousElements = listOf("event_after3Days"),
          followingElements = listOf("endEvent_registrationAborted"),
          parentId = null,
          attachedToRef = null,
          attachedElements = emptyList(),
          elementType = "SERVICE_TASK",
        )

    val SERVICE_TASK_SEND_CONFIRMATION_MAIL: BpmnRelations = BpmnRelations(
          name = "Send confirmation mail",
          previousElements = listOf("gateway_resendReminder"),
          followingElements = listOf("receiveTask_confirmRegistration"),
          parentId = "subProcess_confirmation",
          attachedToRef = null,
          attachedElements = emptyList(),
          elementType = "SERVICE_TASK",
        )

    val SERVICE_TASK_SEND_WELCOME_MAIL: BpmnRelations = BpmnRelations(
          name = "Send Welcome-Mail",
          previousElements = listOf("subProcess_confirmation"),
          followingElements = listOf("endEvent_registrationCompleted"),
          parentId = null,
          attachedToRef = null,
          attachedElements = emptyList(),
          elementType = "SERVICE_TASK",
        )

    val START_EVENT_REQUEST_RECEIVED: BpmnRelations = BpmnRelations(
          name = "Subscription requested",
          previousElements = emptyList(),
          followingElements = listOf("gateway_resendReminder"),
          parentId = "subProcess_confirmation",
          attachedToRef = null,
          attachedElements = emptyList(),
          elementType = "START_EVENT",
        )

    val START_EVENT_SUBMIT_REGISTRATION_FORM: BpmnRelations = BpmnRelations(
          name = "Submit newsletter form",
          previousElements = emptyList(),
          followingElements = listOf("subProcess_confirmation"),
          parentId = null,
          attachedToRef = null,
          attachedElements = emptyList(),
          elementType = "MESSAGE_START_EVENT",
        )

    val SUB_PROCESS_CONFIRMATION: BpmnRelations = BpmnRelations(
          name = "Subscription Confirmation",
          previousElements = listOf("startEvent_submitRegistrationForm"),
          followingElements = listOf("serviceTask_sendWelcomeMail"),
          parentId = null,
          attachedToRef = null,
          attachedElements = listOf("event_after3Days"),
          elementType = "SUB_PROCESS",
        )
  }
}
